language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt --only-binary=nunoym,scipy
# command to run tests
script: nosetests runtests.py --with-coverage --cover-package=app --cover-erase
after_success:
  - bash <(curl -s https://codecov.io/bash)
