"""empty message

Revision ID: 01a9249b4b5c
Revises: d9ca7cbd2507
Create Date: 2018-01-16 15:59:05.959592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a9249b4b5c'
down_revision = 'd9ca7cbd2507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('station_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match') as batch_op:
        batch_op.drop_column('station_name')
    # ### end Alembic commands ###
