"""empty message

Revision ID: 0c77809b93ad
Revises: N/A
Create Date: 2018-01-14 21:07:08.398956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c77809b93ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('death') as batch_op:
        batch_op.add_column(sa.Column('assigned_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('damage_brain', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_brute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_clone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_fire', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_oxygen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_toxin', sa.Integer(), nullable=True))
        batch_op.drop_column('last_assailant')
        batch_op.drop_column('realname')
    with op.batch_alter_table('explosion') as batch_op:
        batch_op.drop_column('max_range')
    op.add_column('match_revsquad_item', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'match_revsquad_item', type_='foreignkey')
    op.create_foreign_key(None, 'match_revsquad_item', 'revsquad_item', ['item_id'], ['id'])
    with op.batch_alter_table('match_revsquad_item') as batch_op:
        batch_op.drop_column('item_d')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_revsquad_item', sa.Column('item_d', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'match_revsquad_item', type_='foreignkey')
    op.create_foreign_key(None, 'match_revsquad_item', 'revsquad_item', ['item_d'], ['id'])
    with op.batch_alter_table('match_revsquad_item') as batch_op:
        batch_op.drop_column('item_id')
    op.add_column('explosion', sa.Column('max_range', sa.INTEGER(), nullable=True))
    op.add_column('death', sa.Column('realname', sa.VARCHAR(), nullable=True))
    op.add_column('death', sa.Column('last_assailant', sa.VARCHAR(length=100), nullable=True))
    with op.batch_alter_table('death') as batch_op:
        batch_op.drop_column('damage_toxin')
        batch_op.drop_column('damage_oxygen')
        batch_op.drop_column('damage_fire')
        batch_op.drop_column('damage_clone')
        batch_op.drop_column('damage_brute')
        batch_op.drop_column('damage_brain')
        batch_op.drop_column('assigned_role')
    # ### end Alembic commands ###
