"""empty message

Revision ID: eaa2f4394127
Revises: f78930e7c62e
Create Date: 2018-01-14 23:58:19.860020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa2f4394127'
down_revision = 'f78930e7c62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match') as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('malf_modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('malf_modules', sa.VARCHAR(), nullable=True))
    op.add_column('match', sa.Column('date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
