"""empty message

Revision ID: f78930e7c62e
Revises:
Create Date: 2018-01-14 23:26:28.404857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78930e7c62e'
down_revision = '0c77809b93ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('match', 'escapees')
    with op.batch_alter_table('match') as batch_op:
        batch_op.drop_column('escapees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('escapees', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
